#Tipos de MySQL:
# MYSQL_HIKARI = Versão de conexão do plugin mais performática porém consome mais memória & cpu
# MYSQL =  Versão de conexão do plugin com as threads do próprio SPIGOT/BUKKIT
# SQLLITE = Utiliza o arquivo "database.sql" como armazenamento.
Database:
  Tipo: SQLITE 
  IP: localhost:3306
  DB: test
  User: root
  Pass: ""
  Debug: true